[package]
name = "s3signer"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["rand/std", "rand/std_rng"]

[dependencies]
hashbrown = "0.15.2"
rand = { version = "0.8.5", default-features = false }

[dev-dependencies]
rand_chacha = "0.3.1"
