[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
fractus-shamir = { path = "crates/shamir" }
[workspace.lints.rust]
[workspace.lints.clippy]
