services:
  postgres:
    container_name: sss-postgres
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-postgres}"
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - ./.cache/postgres/data:/var/lib/postgresql/data
